name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      - name: Set up Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'package.json'

      - name: Install Node.js dependencies
        run: npm i

      - name: Build dist
        run: npm run build

      - name: Commit dist
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
        with:
          add: "dist"
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "[auto] Update compiled version"
