name: Coding Standards

on:
  pull_request_target:
    branches:
      - master

permissions:
  contents: read
  pull-requests: read

jobs:
  check:
    name: Set up and run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository (push)
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      - name: Check out repository (pull_request_target)
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'package.json'

      - name: Install Node.js dependencies
        run: npm i

      - name: Run linters
        uses: wearerequired/lint-action@548d8a7c4b04d3553d32ed5b6e91eb171e10e7bb # v2
        with:
          continue_on_error: false
          eslint: true
